# Generated by Django 5.1.5 on 2025-02-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256, unique=True)),
                ('f_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
