# Generated by Django 5.1.5 on 2025-04-15 21:45

import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(blank=True, max_length=20)),
                ('auth_type', models.CharField(choices=[('local', 'Local Authentication'), ('google', 'Google OAuth2.0')], default='local', max_length=10)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('limit', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=uuid.uuid4, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(default=users.models.one_hour_from_now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('admins', models.ManyToManyField(blank=True, related_name='group_admin', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='group_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
