# Generated by Django 5.1.5 on 2025-03-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_group_admins_alter_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='limit',
            field=models.FloatField(default=0.0),
        ),
    ]
