# Generated by Django 5.1.5 on 2025-02-10 10:31

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('users', '0002_user_auth_type_user_google_id_user_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.AddField(
            model_name='document',
            name='access',
            field=models.CharField(choices=[('ANYONE', 'Anyone'), ('SHARED', 'Shared'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=7),
        ),
        migrations.AddField(
            model_name='document',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='documents', to='users.group'),
        ),
        migrations.AddField(
            model_name='document',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(),
        ),
    ]
