# Generated by Django 5.1.5 on 2025-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_file_name_alter_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.FloatField(default=0.0),
        ),
    ]
