# Generated by Django 5.1.5 on 2025-03-14 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_document_created_at'),
        ('users', '0006_alter_group_admins_alter_group_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='document',
            name='users',
        ),
        migrations.AddField(
            model_name='document',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='users.group'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='access',
            field=models.CharField(choices=[('ANYONE', 'Anyone'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=7),
        ),
        migrations.AlterField(
            model_name='document',
            name='obj_type',
            field=models.CharField(),
        ),
    ]
