# Generated by Django 5.1.5 on 2025-04-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_folder_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='shared',
        ),
    ]
