# Generated by Django 5.1.5 on 2025-03-31 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_folder_file_delete_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'folder', 'user')},
        ),
    ]
