# Generated by Django 5.1.5 on 2025-03-31 20:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_file_unique_together'),
        ('users', '0007_user_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'folder', 'user', 'group')},
        ),
    ]
